
server:
  port: 8080 # Definir a porta que o server irá utilizar
  servlet:
    context-path: /bootcamp #Definir a URL

# É necessário seguir a mesma hierarquia
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: postgres://mxebpxdnaftdag:65cd26914f3908aabbb586b6de2e3cac958a383c6466ba2e91887c873a9e001c@ec2-34-206-8-52.compute-1.amazonaws.com:5432/d8bokgd67pal0f
    username: mxebpxdnaftdag #nome
    password: 65cd26914f3908aabbb586b6de2e3cac958a383c6466ba2e91887c873a9e001c #Senha do postgres criado
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect # Dialeto que será utilizado
    generate-ddl: true
    hibernate:
      ddl-auto: none # Não cria nada automatico


application:
  description: Projeto criado para o bootcamp DIO - Santander / Backend